/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** فحص صحة الخدمة */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** تسجيل الدخول بالبريد/المستخدم وكلمة المرور */
        post: operations["postAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** استبدال كود SSO لمرة واحدة بتوكن حقيقي */
        post: operations["postSsoExchange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** تسجيل حضور (check-in) */
        post: operations["postAttendanceCheckIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** TODO: قائمة الشركات */
        get: operations["listCompanies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** TODO: قائمة المستخدمين */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/work-sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** TODO: قائمة مواقع العمل */
        get: operations["listWorkSites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** TODO: قائمة الورديات */
        get: operations["listShifts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** TODO: سجلات الحضور */
        get: operations["listAttendance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** أنواع الإجازات (يتطلّب leaves.view) */
        get: operations["listLeaveTypes"];
        put?: never;
        /** إنشاء نوع إجازة (يتطلّب leaves.manage_balances) */
        post: operations["createLeaveType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** قائمة طلبات الإجازة للشركة بفلاتر موظف/حالة/فترة (يتطلّب leaves.view) */
        get: operations["listLeaves"];
        put?: never;
        /** تقديم طلب إجازة (لنفسه أو بالنيابة للمخوّلين) */
        post: operations["createLeave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaves/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** طلبات الإجازة للموظف الحالي */
        get: operations["listMyLeaves"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaves/{leave}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** الموافقة على طلب إجازة معلّق (يتطلّب leaves.approve) — يخصم الرصيد */
        post: operations["approveLeave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaves/{leave}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** رفض طلب إجازة معلّق (يتطلّب leaves.approve) */
        post: operations["rejectLeave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user}/leave-balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** أرصدة إجازات موظف (يتطلّب leaves.view) */
        get: operations["listLeaveBalances"];
        /** ضبط/تعديل رصيد إجازة (set/increment) (يتطلّب leaves.manage_balances) */
        put: operations["upsertLeaveBalance"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** TODO: كشوف الرواتب */
        get: operations["listPayroll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** TODO: التقارير */
        get: operations["listReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** TODO: إدارة الـ Webhooks */
        get: operations["listWebhooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integration/employees/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** TODO: مزامنة/استيراد الموظفين */
        post: operations["postEmployeesSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** إصدار التطبيق والـ API */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** تجديد التوكن عبر refresh token */
        post: operations["postAuthRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** تسجيل الخروج (إبطال التوكن الحالي) */
        post: operations["postAuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** المستخدم الحالي مع شركته وأدواره وصلاحياته */
        get: operations["getAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** التحقق من تحدّي 2FA (TOTP أو كود استرداد) وإصدار التوكنات */
        post: operations["postTwoFactorVerify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** توليد سرّ 2FA وإرجاع otpauth URI */
        post: operations["postTwoFactorEnable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** تأكيد تفعيل 2FA وإرجاع أكواد الاسترداد (مرة واحدة) */
        post: operations["postTwoFactorConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** تعطيل 2FA (يتطلب رمزاً صحيحاً) */
        post: operations["postTwoFactorDisable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sso/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** إصدار كود SSO لمرة واحدة لمستخدم هدف (محمي) */
        post: operations["postSsoIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** قائمة أدوار الشركة */
        get: operations["listRoles"];
        put?: never;
        /** إنشاء دور وتعيين صلاحياته */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** قائمة الصلاحيات المتاحة */
        get: operations["listPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** مزامنة أدوار مستخدم */
        post: operations["syncUserRoles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** إسناد صلاحيات مباشرة لمستخدم فوق دوره */
        post: operations["syncUserPermissions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** جلب إعدادات الشركة */
        get: operations["getCompanySettings"];
        /** تعديل إعدادات الشركة */
        put: operations["updateCompanySettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** قائمة أقسام الشركة */
        get: operations["listDepartments"];
        put?: never;
        /** إنشاء قسم */
        post: operations["createDepartment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description الغلاف الموحّد لكل الردود */
        Envelope: {
            /** @description الحمولة الأساسية (كائن/مصفوفة) أو null عند الخطأ */
            data: Record<string, never> | unknown[] | null;
            /** @description بيانات وصفية (ترقيم الصفحات، إجماليات…) */
            meta: Record<string, never>;
            errors: components["schemas"]["Error"][];
        };
        Error: {
            /** @description رمز الخطأ القابل للبرمجة */
            code: string;
            /** @description رسالة بشرية مقروءة */
            message: string;
            /** @description الحقل المرتبط بالخطأ (اختياري) */
            field?: string;
        };
        TokenResponse: {
            access_token: string;
            refresh_token?: string;
            /** @constant */
            token_type: "Bearer";
            /** @description مدة الصلاحية بالثواني */
            expires_in: number;
        };
        CheckInRequest: {
            /**
             * Format: double
             * @description خط العرض
             */
            lat: number;
            /**
             * Format: double
             * @description خط الطول
             */
            lng: number;
            /** @description معرّف الجهاز المربوط */
            device_uid: string;
            /**
             * Format: double
             * @description دقة الموقع بالأمتار
             */
            accuracy: number;
            /**
             * @description هل الموقع مزيّف (Mock Location)؟
             * @default false
             */
            is_mock: boolean;
        };
        AttendanceRecord: {
            id?: string;
            type?: components["schemas"]["AttendanceType"];
            /** Format: date-time */
            recorded_at?: string;
            work_site_id?: string;
            within_geofence?: boolean;
        };
        /**
         * @description نوع التسجيل (دخول/خروج)
         * @enum {string}
         */
        AttendanceType: "in" | "out";
        /**
         * @description نوع الإجازة
         * @enum {string}
         */
        LeaveKind: "hourly" | "daily" | "long" | "sick";
        /**
         * @description حالة الطلب/الموافقة
         * @enum {string}
         */
        RequestStatus: "pending" | "approved" | "rejected" | "auto";
        /**
         * @description نوع الخصم في قواعد العقوبات
         * @enum {string}
         */
        DeductionType: "percent" | "fixed";
        /**
         * @description طريقة احتساب العمل الإضافي
         * @enum {string}
         */
        OvertimeMode: "manual" | "percent" | "fixed_per_hour";
    };
    responses: {
        /** @description استجابة خطأ موحّدة */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "data": null,
                 *       "meta": {},
                 *       "errors": [
                 *         {
                 *           "code": "invalid_credentials",
                 *           "message": "بيانات الدخول غير صحيحة"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description TODO: لم يُعرَّف بعد */
        TodoResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
        /** @description استجابة ناجحة بالصيغة الموحّدة */
        EnvelopeOk: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Envelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description الخدمة تعمل */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "status": "ok",
                     *         "time": "2026-06-03T10:00:00Z"
                     *       },
                     *       "meta": {},
                     *       "errors": []
                     *     }
                     */
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: {
                            /** @constant */
                            status?: "ok";
                            /** Format: date-time */
                            time?: string;
                        };
                    };
                };
            };
        };
    };
    postAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    /** Format: password */
                    password: string;
                    /** @description رمز 2FA إن كان مفعّلاً */
                    otp?: string;
                };
            };
        };
        responses: {
            /** @description نجاح الدخول */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["TokenResponse"];
                    };
                };
            };
            401: components["responses"]["ErrorResponse"];
        };
    };
    postSsoExchange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description كود الدخول الموحّد قصير العمر */
                    code: string;
                };
            };
        };
        responses: {
            /** @description نجاح الاستبدال */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["TokenResponse"];
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
        };
    };
    postAttendanceCheckIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInRequest"];
            };
        };
        responses: {
            /** @description تم تسجيل الحضور */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["AttendanceRecord"];
                    };
                };
            };
            422: components["responses"]["ErrorResponse"];
        };
    };
    listCompanies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TodoResponse"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TodoResponse"];
        };
    };
    listWorkSites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TodoResponse"];
        };
    };
    listShifts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TodoResponse"];
        };
    };
    listAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TodoResponse"];
        };
    };
    listLeaveTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
        };
    };
    createLeaveType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["EnvelopeOk"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    listLeaves: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
        };
    };
    createLeave: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["EnvelopeOk"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    listMyLeaves: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
        };
    };
    approveLeave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leave: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
            403: components["responses"]["ErrorResponse"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    rejectLeave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leave: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    listLeaveBalances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
        };
    };
    upsertLeaveBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    listPayroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TodoResponse"];
        };
    };
    listReports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TodoResponse"];
        };
    };
    listWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TodoResponse"];
        };
    };
    postEmployeesSync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TODO */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
        };
    };
    postAuthRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
            401: components["responses"]["ErrorResponse"];
        };
    };
    postAuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
        };
    };
    getAuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
        };
    };
    postTwoFactorVerify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
            401: components["responses"]["ErrorResponse"];
        };
    };
    postTwoFactorEnable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
        };
    };
    postTwoFactorConfirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    postTwoFactorDisable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
        };
    };
    postSsoIssue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["EnvelopeOk"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["EnvelopeOk"];
            422: components["responses"]["ErrorResponse"];
        };
    };
    listPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
        };
    };
    syncUserRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
        };
    };
    syncUserPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
        };
    };
    getCompanySettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
        };
    };
    updateCompanySettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
        };
    };
    listDepartments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EnvelopeOk"];
        };
    };
    createDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["EnvelopeOk"];
        };
    };
}
